services:
  zookeeper:
    image: zookeeper:3.9.3
    restart: "no"
    ports:
      - "2181:2181"
    healthcheck:
      test: nc -z 127.0.0.1 2181 || exit -1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    restart: "no"
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'Testing Kafka' && nc -z localhost 29092"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    depends_on:
      - zookeeper
    labels:
      amplicode.image: confluent/kafka

  orders:
    build:
      context: .
      dockerfile: orders/Dockerfile
    restart: "no"
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    environment:
      KAFKA_CONTAINER_HOST: kafka:29092
    labels:
      amplicode.image: springboot

  payment:
    build:
      context: .
      dockerfile: payment/Dockerfile
    restart: "no"
    ports:
      - "8082:8082"
    depends_on:
      - kafka
    environment:
      KAFKA_CONTAINER_HOST: kafka:29092
    labels:
      amplicode.image: springboot

  shipping:
    build:
      context: .
      dockerfile: shipping/Dockerfile
    restart: "no"
    ports:
      - "8083:8083"
    depends_on:
      - kafka
    environment:
      KAFKA_CONTAINER_HOST: kafka:29092
    labels:
      amplicode.image: springboot

  notifications:
    build:
      context: .
      dockerfile: notifications/Dockerfile
    restart: "no"
    ports:
      - "8084:8084"
    depends_on:
      - kafka
    environment:
      KAFKA_CONTAINER_HOST: kafka:29092
    labels:
      amplicode.image: springboot
